<?php
$data = array (
  0 => 
  array (
    'cat_id' => '11',
    'cat_name' => '手机促销',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统分类',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '12',
    'cat_name' => '站内快讯',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  3 => 
  array (
    'cat_id' => '4',
    'cat_name' => '3G资讯',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  4 => 
  array (
    'cat_id' => '2',
    'cat_name' => '网店信息',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => '网店信息分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  5 => 
  array (
    'cat_id' => '3',
    'cat_name' => '网店帮助分类',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => '网店帮助分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '6',
    'aricle_num' => '0',
  ),
  6 => 
  array (
    'cat_id' => '5',
    'cat_name' => '新手上路 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  7 => 
  array (
    'cat_id' => '6',
    'cat_name' => '手机常识 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '手机常识 ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  8 => 
  array (
    'cat_id' => '7',
    'cat_name' => '配送与支付 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '配送与支付 ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  9 => 
  array (
    'cat_id' => '8',
    'cat_name' => '服务保证 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  10 => 
  array (
    'cat_id' => '9',
    'cat_name' => '联系我们 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '联系我们 ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  11 => 
  array (
    'cat_id' => '10',
    'cat_name' => '会员中心',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
);
?>