<?php
$data = array (
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '龙之谷',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '49',
    'has_children' => '31',
    'goods_num' => 0,
    'level' => 0,
    'id' => '23',
    'name' => '龙之谷',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '南方电信一区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '57',
    'name' => '南方电信一区',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '南方电信二区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '58',
    'name' => '南方电信二区',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '华中电信一区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '59',
    'name' => '华中电信一区',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '华中电信二区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '60',
    'name' => '华中电信二区',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '西南电信一区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '61',
    'name' => '西南电信一区',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '西南电信二区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '62',
    'name' => '西南电信二区',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '华东电信一区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '63',
    'name' => '华东电信一区',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '华东电信二区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '64',
    'name' => '华东电信二区',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '华东电信三区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '65',
    'name' => '华东电信三区',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '华东电信四区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '66',
    'name' => '华东电信四区',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '华东电信五区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '67',
    'name' => '华东电信五区',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '华东电信六区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '68',
    'name' => '华东电信六区',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '华东电信七区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '69',
    'name' => '华东电信七区',
  ),
  164 => 
  array (
    'cat_id' => '164',
    'cat_name' => '4服-塔姐之吻',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '164',
    'name' => '4服-塔姐之吻',
  ),
  161 => 
  array (
    'cat_id' => '161',
    'cat_name' => '1服-龙魂传世',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '161',
    'name' => '1服-龙魂传世',
  ),
  165 => 
  array (
    'cat_id' => '165',
    'cat_name' => '5服-龙之纹章',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '165',
    'name' => '5服-龙之纹章',
  ),
  162 => 
  array (
    'cat_id' => '162',
    'cat_name' => '2服-龙行流云',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '162',
    'name' => '2服-龙行流云',
  ),
  166 => 
  array (
    'cat_id' => '166',
    'cat_name' => '6服-天启之光',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '166',
    'name' => '6服-天启之光',
  ),
  163 => 
  array (
    'cat_id' => '163',
    'cat_name' => '3服-杰哥之泪',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '163',
    'name' => '3服-杰哥之泪',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '华南电信一区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '70',
    'name' => '华南电信一区',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '华南电信二区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '71',
    'name' => '华南电信二区',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '华南电信三区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '16',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '72',
    'name' => '华南电信三区',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '华南电信四区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '17',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '73',
    'name' => '华南电信四区',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '华南电信五区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '18',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '74',
    'name' => '华南电信五区',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '华南电信六区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '19',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '75',
    'name' => '华南电信六区',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '西部电信一区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '76',
    'name' => '西部电信一区',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '华北网通一区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '21',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '77',
    'name' => '华北网通一区',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '华北网通二区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '22',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '78',
    'name' => '华北网通二区',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '华北网通三区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '23',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '79',
    'name' => '华北网通三区',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '华北网通四区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '24',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '80',
    'name' => '华北网通四区',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '华北网通五区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '25',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '81',
    'name' => '华北网通五区',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '东北网通一区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '26',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '82',
    'name' => '东北网通一区',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '东北网通二区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '27',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '83',
    'name' => '东北网通二区',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '东北网通三区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '28',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '84',
    'name' => '东北网通三区',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '山东网通区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '29',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '85',
    'name' => '山东网通区',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '电信畅玩区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '86',
    'name' => '电信畅玩区',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '风之轻吟',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '88',
    'name' => '风之轻吟',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '网通畅玩区',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '31',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '87',
    'name' => '网通畅玩区',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '神之叹息',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '89',
    'name' => '神之叹息',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => '充值点卡',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '148',
    'name' => '充值点卡',
  ),
  151 => 
  array (
    'cat_id' => '151',
    'cat_name' => '点卡',
    'measure_unit' => '',
    'parent_id' => '148',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '151',
    'name' => '点卡',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => '盛大一卡通',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '149',
    'name' => '盛大一卡通',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '地下城与勇士',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '16',
    'name' => '地下城与勇士',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '测试区',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '19',
    'name' => '测试区',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '测试服',
    'measure_unit' => '万金币',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '22',
    'name' => '测试服',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '体验区',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => '体验区',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '体验服',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '21',
    'name' => '体验服',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '电信区',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '17',
    'name' => '电信区',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '网通区',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '18',
    'name' => '网通区',
  ),
  145 => 
  array (
    'cat_id' => '145',
    'cat_name' => '第九大陆',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '145',
    'name' => '第九大陆',
  ),
  152 => 
  array (
    'cat_id' => '152',
    'cat_name' => '上海一区',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '152',
    'name' => '上海一区',
  ),
  155 => 
  array (
    'cat_id' => '155',
    'cat_name' => '沃特福德',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '155',
    'name' => '沃特福德',
  ),
  156 => 
  array (
    'cat_id' => '156',
    'cat_name' => '迈修利安',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '156',
    'name' => '迈修利安',
  ),
  153 => 
  array (
    'cat_id' => '153',
    'cat_name' => '华北一区',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '153',
    'name' => '华北一区',
  ),
  158 => 
  array (
    'cat_id' => '158',
    'cat_name' => '丹配拉',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '158',
    'name' => '丹配拉',
  ),
  157 => 
  array (
    'cat_id' => '157',
    'cat_name' => '宾佩里',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '157',
    'name' => '宾佩里',
  ),
  154 => 
  array (
    'cat_id' => '154',
    'cat_name' => '广东一区',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '154',
    'name' => '广东一区',
  ),
  159 => 
  array (
    'cat_id' => '159',
    'cat_name' => '洛诺斯比尔',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '159',
    'name' => '洛诺斯比尔',
  ),
  160 => 
  array (
    'cat_id' => '160',
    'cat_name' => '罗纳德城',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '160',
    'name' => '罗纳德城',
  ),
  146 => 
  array (
    'cat_id' => '146',
    'cat_name' => '腾讯业务',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '146',
    'name' => '腾讯业务',
  ),
  150 => 
  array (
    'cat_id' => '150',
    'cat_name' => '经典业务',
    'measure_unit' => '',
    'parent_id' => '146',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '150',
    'name' => '经典业务',
  ),
  147 => 
  array (
    'cat_id' => '147',
    'cat_name' => 'QQ会员',
    'measure_unit' => '',
    'parent_id' => '150',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '147',
    'name' => 'QQ会员',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '征途2',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '90',
    'name' => '征途2',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '电信区',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '32',
    'goods_num' => 0,
    'level' => 1,
    'id' => '91',
    'name' => '电信区',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '龙腾四海',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '100',
    'name' => '龙腾四海',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '风驰九州',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '116',
    'name' => '风驰九州',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '逐鹿江湖',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '97',
    'name' => '逐鹿江湖',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '中原侠骨',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '113',
    'name' => '中原侠骨',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '风雨同舟',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '94',
    'name' => '风雨同舟',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '凤舞凌云',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '110',
    'name' => '凤舞凌云',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '锦绣黄沙',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '107',
    'name' => '锦绣黄沙',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '龙门飞甲',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '123',
    'name' => '龙门飞甲',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '雷动八荒',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '104',
    'name' => '雷动八荒',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '傲视群雄',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '120',
    'name' => '傲视群雄',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '浩然正气',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '101',
    'name' => '浩然正气',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => '君临天下',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '117',
    'name' => '君临天下',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '碧血烽烟',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '98',
    'name' => '碧血烽烟',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '九霄龙吟',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '114',
    'name' => '九霄龙吟',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '卧虎琴心',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '95',
    'name' => '卧虎琴心',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '明月冰河',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '111',
    'name' => '明月冰河',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '烽火连天',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '108',
    'name' => '烽火连天',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '普天同庆',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '124',
    'name' => '普天同庆',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '倚剑柔情',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '105',
    'name' => '倚剑柔情',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '斗转星移',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '121',
    'name' => '斗转星移',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '烈火雄心',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '102',
    'name' => '烈火雄心',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '江山夜雨',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '118',
    'name' => '江山夜雨',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '月满华夏',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '99',
    'name' => '月满华夏',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '狂啸九天',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '115',
    'name' => '狂啸九天',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '笑傲仙侣',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '96',
    'name' => '笑傲仙侣',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '皇者大陆',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '112',
    'name' => '皇者大陆',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '携手同行',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '93',
    'name' => '携手同行',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '盛世龙庭',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '109',
    'name' => '盛世龙庭',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '气贯华山',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '106',
    'name' => '气贯华山',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '豪情壮志',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '122',
    'name' => '豪情壮志',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '横扫千军',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '103',
    'name' => '横扫千军',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '丽景清风',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '119',
    'name' => '丽景清风',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '网通区',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '20',
    'goods_num' => 0,
    'level' => 1,
    'id' => '92',
    'name' => '网通区',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '醉卧沙场',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '132',
    'name' => '醉卧沙场',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '虎啸山河',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '129',
    'name' => '虎啸山河',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '铁马同舟',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '126',
    'name' => '铁马同舟',
  ),
  142 => 
  array (
    'cat_id' => '142',
    'cat_name' => '侠者风云',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '142',
    'name' => '侠者风云',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '仗剑天涯',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '139',
    'name' => '仗剑天涯',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '雪域风云',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '136',
    'name' => '雪域风云',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => '星月同辉',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '133',
    'name' => '星月同辉',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '紫电清霜',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '130',
    'name' => '紫电清霜',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '傲视春秋',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '127',
    'name' => '傲视春秋',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => '东成西就',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '143',
    'name' => '东成西就',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '大漠四海',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '140',
    'name' => '大漠四海',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '狂剑千里',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '137',
    'name' => '狂剑千里',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '英雄国度',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '134',
    'name' => '英雄国度',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '碧海紫禁',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '131',
    'name' => '碧海紫禁',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '逍遥非诚',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '128',
    'name' => '逍遥非诚',
  ),
  144 => 
  array (
    'cat_id' => '144',
    'cat_name' => '龙凤吉祥',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '144',
    'name' => '龙凤吉祥',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '携手同行',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '125',
    'name' => '携手同行',
  ),
  141 => 
  array (
    'cat_id' => '141',
    'cat_name' => '唯我独尊',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '141',
    'name' => '唯我独尊',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => '沙场雄风',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '138',
    'name' => '沙场雄风',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '纵横乾坤',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '135',
    'name' => '纵横乾坤',
  ),
);
?>