<p class="share_this">
	<a title="转播到新浪微博" class="st_sina" href="http://v.t.sina.com.cn/share/share.php?title=<?php echo $this->_var['goods']['goods_name']; ?>%E4%BB%85%E5%94%AE<?php echo $this->_var['goods']['promote_price']; ?>%2C+%E5%BF%AB%E6%9D%A5%E6%8A%A2%E8%B4%AD%E5%90%A7!+-+ESUP%E7%BD%91%E6%B8%B8++%E5%9C%B0%E5%9D%80:+&url=http://www.esup.cn<?php echo $this->_var['this_url']; ?>&source=bookmark&appkey=3987673739&pic=http://www.esup.cn/<?php echo $this->_var['option']['static_path']; ?><?php echo $this->_var['goods']['goods_img']; ?>" rel="external">新浪微博</a>
	<a title="转播到腾讯微博" class="st_qq" href="http://share.v.t.qq.com/index.php?c=share&a=index&assname=&pic=http://www.esup.cn/<?php echo $this->_var['option']['static_path']; ?><?php echo $this->_var['goods']['goods_img']; ?>&appkey=100239076&title=<?php echo $this->_var['goods']['goods_name']; ?>%E4%BB%85%E5%94%AE<?php echo $this->_var['goods']['promote_price']; ?>%2C+%E5%BF%AB%E6%9D%A5%E6%8A%A2%E8%B4%AD%E5%90%A7!+-+ESUP%E7%BD%91%E6%B8%B8++%E5%9C%B0%E5%9D%80:+&url=http://www.esup.cn<?php echo $this->_var['this_url']; ?>" rel="external">腾讯微博</a>
	<a title="转播到搜狐微博" class="st_sohu" href="http://t.sohu.com/third/post.jsp?&url=http://www.esup.cn<?php echo $this->_var['this_url']; ?>&title=<?php echo $this->_var['goods']['goods_name']; ?>%E4%BB%85%E5%94%AE<?php echo $this->_var['goods']['promote_price']; ?>%2C+%E5%BF%AB%E6%9D%A5%E6%8A%A2%E8%B4%AD%E5%90%A7!+-+ESUP%E7%BD%91%E6%B8%B8++%E5%9C%B0%E5%9D%80:+&content=utf-8&pic=http://www.esup.cn/<?php echo $this->_var['option']['static_path']; ?><?php echo $this->_var['goods']['goods_img']; ?>&appkey=nk6uBsbY2diERiJgWo73" rel="external">搜狐微博</a>
	<a title="转播到网易微博" class="st_163" href="http://t.163.com/article/user/checkLogin.do?link=http://www.esup.cn/&source=Esup%E7%BD%91%E6%B8%B8&info=<?php echo $this->_var['goods']['goods_name']; ?>%E4%BB%85%E5%94%AE<?php echo $this->_var['goods']['promote_price']; ?>%2C+%E5%BF%AB%E6%9D%A5%E6%8A%A2%E8%B4%AD%E5%90%A7!+-+ESUP%E7%BD%91%E6%B8%B8++%E5%9C%B0%E5%9D%80:+http://www.esup.cn<?php echo $this->_var['this_url']; ?>&images=http://www.esup.cn/<?php echo $this->_var['option']['static_path']; ?><?php echo $this->_var['goods']['goods_img']; ?>&togImg=true" rel="external">网易微博</a>
	<a title="分享到人人网" class="st_renren" href="http://widget.renren.com/dialog/share?resourceUrl=http://www.esup.cn<?php echo $this->_var['this_url']; ?>&pic=http://www.esup.cn/<?php echo $this->_var['option']['static_path']; ?><?php echo $this->_var['goods']['goods_img']; ?>&charset=UTF-8&title=<?php echo $this->_var['goods']['goods_name']; ?>&description=<?php echo $this->_var['goods']['goods_name']; ?>%E4%BB%85%E5%94%AE<?php echo $this->_var['goods']['promote_price']; ?>%2C+%E5%BF%AB%E6%9D%A5%E6%8A%A2%E8%B4%AD%E5%90%A7!+-+ESUP%E7%BD%91%E6%B8%B8&api_key=b3553f82a76b4038b808c0eef8ca8617" rel="external">人人网</a>
	<a title="分享到开心网" class="st_kaixin" href="http://www.kaixin001.com/rest/records.php?content=<?php echo $this->_var['goods']['goods_name']; ?>%E4%BB%85%E5%94%AE<?php echo $this->_var['goods']['promote_price']; ?>%2C+%E5%BF%AB%E6%9D%A5%E6%8A%A2%E8%B4%AD%E5%90%A7!+-+ESUP%E7%BD%91%E6%B8%B8&url=http://www.esup.cn<?php echo $this->_var['this_url']; ?>&starid=0&aid=100023098&style=11&pic=http://www.esup.cn/<?php echo $this->_var['option']['static_path']; ?><?php echo $this->_var['goods']['goods_img']; ?>" rel="external">开心网</a>
	<a title="分享到Facebook" class="st_facebook" href="https://www.facebook.com/sharer/sharer.php?u=http://www.esup.cn<?php echo $this->_var['this_url']; ?>&t=<?php echo $this->_var['goods']['goods_name']; ?>%E4%BB%85%E5%94%AE<?php echo $this->_var['goods']['promote_price']; ?>%2C+%E5%BF%AB%E6%9D%A5%E6%8A%A2%E8%B4%AD%E5%90%A7!+-+ESUP%E7%BD%91%E6%B8%B8&pic=http://www.esup.cn/<?php echo $this->_var['option']['static_path']; ?><?php echo $this->_var['goods']['goods_img']; ?>" rel="external">Facebook</a>
	<a title="转播到Twitter" class="st_twitter" href="https://twitter.com/intent/tweet?text=<?php echo $this->_var['goods']['goods_name']; ?>%E4%BB%85%E5%94%AE<?php echo $this->_var['goods']['promote_price']; ?>%2C+%E5%BF%AB%E6%9D%A5%E6%8A%A2%E8%B4%AD%E5%90%A7!+-+ESUP%E7%BD%91%E6%B8%B8++%E5%9C%B0%E5%9D%80:+http://www.esup.cn<?php echo $this->_var['this_url']; ?>" rel="external">Twitter</a>
<!--<a title="存入Google书签" class="st_gg" href="https://www.google.com/bookmarks/mark?op=add&bkmk=http://www.esup.cn<?php echo $this->_var['this_url']; ?>&title=<?php echo $this->_var['goods']['goods_name']; ?>%E4%BB%85%E5%94%AE<?php echo $this->_var['goods']['promote_price']; ?>%2C+%E5%BF%AB%E6%9D%A5%E6%8A%A2%E8%B4%AD%E5%90%A7!+-+ESUP%E7%BD%91%E6%B8%B8" rel="external">Google书签</a> -->
</p>